#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliasing
alias dco='docker-compose'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias git=hub

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

export PATH="$HOME/.bin:$PATH"

# Sets Hub autocompletions
fpath=(~/.zsh_completions $fpath)
autoload -U compinit && compinit
